version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"

sphinx:
   configuration: docs/docs/conf.py

python:
   install:
    - requirements: docs/support/requirements.txt
    - method: pip
      path: .
